import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { TooltipProvider } from "@/components/ui/tooltip";
import { Toaster } from "sonner";
import { BackgroundEffects } from "@/ui/cinematic-ember";
import UpdateNotification from "@/components/UpdateNotification";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const isProd = process.env.NODE_ENV === "production";

  // NOTE: Hardened CSP for Electron + Next.js.
  // - 'unsafe-inline' for styles is required by Next.js/Tailwind in some modes, but we can try to restrict scripts.
  // - 'unsafe-eval' is often needed by dev tools or some polyfills, but in prod we should try to remove it if possible.
  //   However, Next.js App Router often requires 'unsafe-inline' for hydration scripts unless we use nonces/hashes.
  //   Since this is a static export, we can't easily generate per-request nonces.
  //   We will keep 'unsafe-inline' for now but remove 'unsafe-eval' and 'blob:'/'data:' from script-src to harden it.
  //   We also restrict connect-src to 'self' (IPC is handled via preload, not fetch).
  const csp = `
    default-src 'self';
    script-src 'self' 'unsafe-inline';
    style-src 'self' 'unsafe-inline';
    img-src 'self' data: blob:;
    font-src 'self';
    connect-src 'self';
    object-src 'none';
    base-uri 'self';
    frame-ancestors 'none';
  `.replace(/\s{2,}/g, " ").trim();

  return (
    <html lang="en">
      <head>
        {/* Only enforce strict CSP in production */}
        {isProd && (
          <meta httpEquiv="Content-Security-Policy" content={csp} />
        )}
        <meta name="referrer" content="no-referrer" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <BackgroundEffects />
        <TooltipProvider delayDuration={200}>
          {children}
        </TooltipProvider>
        <Toaster position="top-center" richColors />
        <UpdateNotification />
      </body>
    </html>
  );
}
